### ISSUE TITLE
QuadNodeCartesianEuclid/QuadNodePolarEuclid::getCellID uses wrong integer types

### ISSUE THREAD

**Issue by michitux** [kit-parco/networkit#1]
As clang notices, `QuadNodeCartesianEuclid/QuadNodePolarEuclid::getCellID` expect that an integer of type `index` might be `-1`, but this type is unsigned. Note also that this method tries to return `-1` in some cases even though its result type is `index`, which is unsigned. Here the compiler warnings:

```
networkit/cpp/io/test/../../generators/quadtree/QuadNodePolarEuclid.h:665:21: warning: comparison of unsigned expression >= 0 is always true [-Wtautological-compare]
                                if (childresult >= 0) return childresult;
                                    ~~~~~~~~~~~ ^  ~
```

```
networkit/cpp/io/test/../../generators/quadtree/QuadNodeCartesianEuclid.h:532:21: warning: comparison of unsigned expression >= 0 is always true [-Wtautological-compare]
                                if (childresult >= 0) return childresult;
                                    ~~~~~~~~~~~ ^  ~
```

[Edit]: Actually, it seems there are even more methods affected by the same bug. Have a look at the compiler log of [this travis job](https://travis-ci.org/kit-parco/networkit/jobs/198574045).

**Comment by mlooz** [comment]
You're right. I don't know what I was thinking when I wrote that. I'll push a fix.

Am 06.02.2017 um 10:12 schrieb Michael Hamann:
> As clang notices, `QuadNodeCartesianEuclid/QuadNodePolarEuclid::getCellID` expect that an integer of type `index` might be `-1`, but this type is unsigned. Note also that this method tries to return `-1` in some cases even though its result type is `index`, which is unsigned. Here the compiler warnings:
> 
> ```
> networkit/cpp/io/test/../../generators/quadtree/QuadNodePolarEuclid.h:665:21: warning: comparison of unsigned expression >= 0 is always true [-Wtautological-compare]
>                                 if (childresult >= 0) return childresult;
>                                     ~~~~~~~~~~~ ^  ~
> ```
> 
> ```
> networkit/cpp/io/test/../../generators/quadtree/QuadNodeCartesianEuclid.h:532:21: warning: comparison of unsigned expression >= 0 is always true [-Wtautological-compare]
>                                 if (childresult >= 0) return childresult;
>                                     ~~~~~~~~~~~ ^  ~
> ```
> 
>
