### ISSUE TITLE
Automatically remove incident edges on removeNode(u)

### ISSUE THREAD

**Issue by kolja-esders** [kit-parco/networkit#10]
During the last meeting we decided to simplify the deletion process of a node by automatically removing the adjacent edges.

I encountered the following note in the Graph.h file:

@note Although it would be convenient to remove all incident edges at the same time, this causes complications for dynamic applications. Therefore, removeNode is an atomic event. All incident edges need to be removed first and an exception is thrown otherwise.

Does anyone know how these specific complications look like? Should we proceed with the task or cancel it? @hmeyerhenke

**Comment by hmeyerhenke** [comment]
Elisabetta will look into a possible problem for dynamic applications.
Probably this is not true any more for the way they are implemented now.


Am 28.03.17 um 23:43 schrieb Kolja Esders:

**Comment by kolja-esders** [comment]
@ebergamini what is the status on this one? Is it okay to automatically remove the adjacent nodes or are there actual issues for dynamic applications?

**Comment by ebergamini** [comment]
@kolja-esders we haven't found any reason why it would be a problem to automatically remove all adjacent edges. The only thing that comes to my mind is that if one accidentally removes a node, he cannot easily "undo" the deletion (whereas if edges are deleted one by one, the user can always reinsert an edge). Do you think this is acceptable?

**Comment by hmeyerhenke** [comment]
Maybe parallelism was a reason back then. On the other hand, right now I
do not see how an "atomic delete" is worse than deleting all the edges
seperately.

Anyone?

Am 04.05.17 um 13:19 schrieb ebergamini:
