### ISSUE TITLE
SCONS build failed

### ISSUE THREAD

**Issue by JSybrandt** [kit-parco/networkit#100]
Hey, I'm trying to build the c++ shared library.
I ran the latest stable version of scons and got an error that tabs/spacing was messed up on line 71
So I fixed that and then got an error that the command argument "-std=None" was provided

g++: error: unrecognized command line option '-std=None'
scons: *** [.buildOpt/algebraic/CSRMatrix.os] Error 1

**Comment by JSybrandt** [comment]
Update, I see the build.conf, but it is not clear to me what I need to change to build

**Comment by JSybrandt** [comment]
Double Update, after fixing the tab error, I noticed that adding --std=c++11 fixes my issue.
Build succeeded.

**Comment by kolja-esders** [comment]
Hey @JSybrandt, we are aware of the issue and will provide a minor release in the near future. Thanks.
