### ISSUE TITLE
Node labels in networkit

### ISSUE THREAD

**Issue by wybert** [kit-parco/networkit#106]
I need use networkit to deal with my graph like this:

      graph [
      node [
        id 0
        label "1"
      ]
      node [
        id 1
        label "2"
      ]
      node [
        id 2
        label "3"
      ]
      node [
        id 3
        label "5"
      ]
      node [
        id 4
        label "20"
      ]
      edge [
        source 0
        target 1
      ]
      edge [
        source 0
        target 2
      ]
      edge [
        source 0
        target 3
      ]
      edge [
        source 0
        target 4
      ]
    ]

I use python to deal with my data:

    from networkit import * 
    G = graphio.readGraph("test.gml",Format.GML) 
    print(G.nodes())

I get:

    [0, 1, 2, 3, 4]
**My questions is**-is there any way to deal with the node labels in my data? I need to use this label as an 'ID' to correspond with my whole data set for further analysis.

**Comment by hmeyerhenke** [comment]
Node attributes are to be handled by the application. Thus, use a data structure that maps from the NetworKit node IDs to your labels and/or vice versa.

**Comment by wybert** [comment]
@hmeyerhenke Is NetworKit node IDs `[0, 1, 2, 3, 4]`  correspond with the IDs in my Graph data. When I change the the ID 0-->5 in my data, like:
```  graph [
  node [
    id 5
    label "1"
  ]
  node [
    id 1
    label "2"
  ]
  node [
    id 2
    label "3"
  ]
  node [
    id 3
    label "5"
  ]
  node [
    id 4
    label "20"
  ]
  edge [
    source 0
    target 1
  ]
  edge [
    source 0
    target 2
  ]
  edge [
    source 0
    target 3
  ]
  edge [
    source 0
    target 4
  ]
]
```
the I read the Graph use python,
```from networkit import * 
G = graphio.readGraph("test.gml",Format.GML) 
print(G.nodes())
```
I get the same:
`[0, 1, 2, 3, 4]`

It's seems like Networkit rebuilt the IDs in my Data. How  Networkit handle the IDs? Is the IDs handled by Networkit  correspond with the order of the nodes in my data? So that the node ID `[0, 1, 2, 3, 4]` in Networkit is correspond with the node ID `5, 1, 2, 3, 4`  in my data?

**Comment by hmeyerhenke** [comment]
The NetworKit node IDs correspond to the order in which the nodes were created.

**Comment by wybert** [comment]
@hmeyerhenke I am confusing about that.  Dose Networkit handle the graph parallelly when I load the graph? If so, I think there is no way to use a data structure that maps from the NetworKit node IDs to my labels.

**Comment by hmeyerhenke** [comment]
Internally, nodes are stored in a std::vector. The index of the vector is the internal ID. If you have an additional vector that can mediate between the internal indices and your IDs, you should be in the game.

**Comment by wybert** [comment]
@hmeyerhenke Get it, thank you)
