### ISSUE TITLE
NetworKit as an Anaconda package?

### ISSUE THREAD

**Issue by habedi** [kit-parco/networkit#112]
Hi,
I'm not sure it's the right place to ask or not, but do you have any plans to publish NetworKit as an anaconda package in the future?

Thanks.

**Comment by hmeyerhenke** [comment]
Hi,
There are no concrete plans yet. This is something you might want to post to the mailing list to open a broader discussion.

Best,
Henning

**Comment by habedi** [comment]
Thank you.
