### ISSUE TITLE
Cannot import Networkit after successful installation

### ISSUE THREAD

**Issue by svilella** [kit-parco/networkit#119]
After struggling a bit I managed to pip-install Networkit in a Python 3.6 Anaconda environment (I'm on OsX High Sierra). I was able to import it only once though, I tried to do it again immediately after but I got this error:

```
ImportError: dlopen(//anaconda/envs/py36/lib/python3.6/site-packages/_NetworKit.cpython-36m-darwin.so, 2): Symbol not found: _GOMP_parallel
  Referenced from: //anaconda/envs/py36/lib/python3.6/site-packages/_NetworKit.cpython-36m-darwin.so
  Expected in: flat namespace
 in //anaconda/envs/py36/lib/python3.6/site-packages/_NetworKit.cpython-36m-darwin.so
```

I think it has something to do with gcc but I don't know how to solve it.

**Comment by avdgrinten** [comment]
GOMP is the GCC OpenMP implementation. Maybe you're missing some library packages? I'm neither an OSX nor an Anaconda expert so I cannot give more concrete advice here.

@kolja-esders @eug93 Any additional comments?

**Comment by svilella** [comment]
I think (but I am absolutely no expert so please correct me) that in order for GCC to support OpenMP I have to install it (using Homebrew) with `brew install gcc --without-multilib` but it doesn't work, since it tells me `Warning: gcc: this formula has no --without-multilib option so it will be ignored!`, and I am not able to find a workaround anywhere.

**Comment by svilella** [comment]
Brief update: I removed GCC and installed clang-omp (which should be included in `brew llvm`), and uninstalled/reinstalled networkit. The error I am getting is now

`ImportError: dlopen(//anaconda/envs/py36/lib/python3.6/site-packages/_NetworKit.cpython-36m-darwin.so, 2): Symbol not found: __ZTINSt8ios_base7failureB5cxx11E
  Referenced from: //anaconda/envs/py36/lib/python3.6/site-packages/_NetworKit.cpython-36m-darwin.so
  Expected in: /usr/lib/libstdc++.6.0.9.dylib
 in //anaconda/envs/py36/lib/python3.6/site-packages/_NetworKit.cpython-36m-darwin.so`

but I am not able to interpret this so I'll stop here and wait for someone who knows better.

**Comment by svilella** [comment]
`g++ -v` output is:
`Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 9.0.0 (clang-900.0.39.2)
Target: x86_64-apple-darwin17.3.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin`

**Comment by eug93** [comment]
The output of `g++ -v` is the same as in my machine, to make NetworKit use the homebrew version of gcc it would make sense to build it from source as suggested by @kolja-esders and then install it with `pip3 install -e ./`. Detailed instructions can be found at [this](https://networkit.iti.kit.edu/get_started.html) address. Make sure to specify the correct compiler in the `build.conf` file (e.g. `cpp = g++-7`).

**Comment by svilella** [comment]
Hi! Thanks for your suggestions. I did everything as described in the instructions, and specified the correct compiler in the `build.conf`. Installation was successful but again I got the same error. I got the name of the compiler simply by writing `g++` in the terminal and giving a double tab to get the list of available g++ compilers; I chose g++-7. Is there anything else I can do to fix this?

**Comment by svilella** [comment]
Unfortunately I couldn't manage to solve this issue, so I had to move to another pc and install it on a linux distro. By the way as soon as I have time I will try to solve it and I'll post here, in case someone founds himself in the same situation. Thanks for your help.

**Comment by hmeyerhenke** [comment]
We are looking forward to your solution, thanks!

**Comment by kolja-esders** [comment]
Please comment once you found a solution and we will reopen this issue accordingly.
