### ISSUE TITLE
Bipartite graphs on Networkit

### ISSUE THREAD

**Issue by svilella** [kit-parco/networkit#120]
I am working with a huge bipartite graph, and the calculation of the projections is computationally very demanding. On the cluster I usually use Networkit, which of course is much more efficient than anything else when you have a lot of cores at your disposal, but I couldn't find any algorithm or function related to bipartite graphs. So I had to stick to the `networkx.algorithms.bipartite` module, but if I specify even a simple function for the calculation of the weights to be used in the projections with the `bipartite.generic_weighted_projected_graph()` function, the (quite powerful) cluster I am using simply won't make it.
Are you planning on extending Networkit to bipartite graphs? Is there any function or algorithm that already exists that maybe I missed?

**Comment by hmeyerhenke** [comment]
There are no special arrangements so far for handling bipartite graphs more efficiently than ordinary graphs.

Two questions would clarify your request for me: What do you want to compute exactly? Why can't it be done with what is already there?

**Comment by avdgrinten** [comment]
I'm closing this as no further info about the issue was provided. Please comment if you want it reopened.
