### ISSUE TITLE
LAMG testSmallGraphs is runtime-dependent

### ISSUE THREAD

**Issue by kolja-esders** [kit-parco/networkit#125]
Currently, the `testSmallGraphs` test for `LAMG` requires the solver to converge within a given time frame. Depending on the execution environment (e.g. Travis) this might lead to a failed test. Should probably be a benchmark instead.

**Comment by hmeyerhenke** [comment]
Yes, if time is the only criterion, then adapt it to be a typical benchmark (use a larger graph then, I guess). Keep a test that is not timing-related.

**Comment by avdgrinten** [comment]
For now I'm removing the timeout. If this becomes a problem in the future, we should consider setting a reasonable iteration limit.
