### ISSUE TITLE
C++ in Jupyter: check this out, possibly useful for NetworKit developers

### ISSUE THREAD

**Issue by clstaudt** [kit-parco/networkit#127]
https://hub.mybinder.org/user/quantstack-xeus-cling-lje33x50/notebooks/notebooks/xcpp.ipynb

**Comment by avdgrinten** [comment]
Unfortunately, the link is broken :D

**Comment by clstaudt** [comment]
I was referring to this: https://github.com/QuantStack/xeus-cling
and wanted to link to the demo: https://t.co/vEOWLzkkqL

**Comment by avdgrinten** [comment]
This is indeed a nice feature. I close this issue but leave #166 open for now.
