### ISSUE TITLE
Graph.forEdges() iterator documentation

### ISSUE THREAD

**Issue by svilella** [kit-parco/networkit#135]
Referring to [this](https://stackoverflow.com/questions/49319722/usage-of-foredges-iterator-in-networkit-python) question on stackoverflow, I would suggest to add some simple example for the usage of the forEdges iterator, because the documentation doesn't really explain a lot and no example can be found anywhere. This iterator may actually be very useful, maybe with some further explanation in the Jupyter Notebook guide!

**Comment by hmeyerhenke** [comment]
Kolja, can you please do that? We should indeed have more examples in notebooks on how to use specific features/algorithms. One step at a time but steadily...

**Comment by svilella** [comment]
Indeed! By the way, until that moment there's a good answer in that stackoverflow question which also explains what a GraphEvent is and how to use it. It's very useful and I think it's a good starting point to build some examples. Thanks for your work!

**Comment by avdgrinten** [comment]
@eug93's SO answer resolves this question.
