### ISSUE TITLE
installation failure on windows through !pip3 install networkx

### ISSUE THREAD

**Issue by gigglegrig** [kit-parco/networkit#145]
I am installing networkit on windows10 machine using `!pip3 install networkit`, but it returns error saying I don't have up-to-date binary compiler, such as g++ and clang++.

The error message is attached below, you can see that the gcc/g++ version is 6.3.0
Besides, my computer can run other python graphical packages smoothly, i.e. iGraph/NetworkX

![image](https://user-images.githubusercontent.com/26666987/38463727-ebd8e60c-3ace-11e8-81a5-6436d12250f6.png)
Please help.

Also can anyone tell me if I want to use the EstimateBetweenness/EstimateCloseness on a graph with 10Million edges and 1Million vertices, how long will it take?

**Comment by eug93** [comment]
I am not very familiar with Windows and, as we mentioned in the [Known Issues](https://github.com/kit-parco/networkit#known-issues), NetworKit is not guaranteed to be build successfully on a Windows machine. 
By looking at your error code it seems that you are using mingw, have you tried to use Cygwin?
If the problem persists I would suggest to work in a Linux environment. However, if anyone has a better knowledge of Windows, help is appreciated.

**Comment by avdgrinten** [comment]
It might make sense to install NetworKit using WSL (i.e. Windows Subsystem for Linux).

**Comment by kolja-esders** [comment]
Hi @gigglegrig, please also take a look at the [corresponding section in the Get Started guide](https://networkit.iti.kit.edu/get_started.html#windows) on the official networkit website.

As @avdgrinten already mentioned, the recommended way to use NetworKit on Windows 10 is to make use of WSL. This should work without any issues. Please let us know otherwise.

**Comment by gigglegrig** [comment]
@eug93 @avdgrinten  Thanks for all your suggestions, I will definitely try those approaches. As a side question, do you have any metrics on the performance comparison between iGraph and Networkit?

**Comment by hmeyerhenke** [comment]
@gigglegrig, see the NetworKit journal paper. It contains performance comparisons with igraph and graph-tool ((nearly) all favorable for NetworKit):
C. Staudt, A. Sazonovs and H. Meyerhenke: NetworKit: A Tool Suite for Large-scale Complex Network Analysis. Network Science 4(4), pp. 508-530, December 2016. Cambridge University Press.
arXiv preprint: http://arxiv.org/abs/1403.3005

**Comment by avdgrinten** [comment]
This seems to be resolved by using WSL.
