### ISSUE TITLE
QXcbConnection: Could not connect to display

### ISSUE THREAD

**Issue by Jessime** [kit-parco/networkit#147]
If I use my university cluster to do:
1. `pip install networkit` 
2.  `ipython`
3. `In [1]: import networkit`

It immediately crashes with the error:

```
QXcbConnection: Could not connect to display 
Aborted
```

and the ipython REPL closes. It seems related to this issue https://github.com/ipython/ipython/issues/10627. And I was able to fix it by running

```bash
export QT_QPA_PLATFORM='offscreen'
```

as suggested in this [comment](https://github.com/ipython/ipython/issues/10627#issuecomment-328198184). I don't know if there's anything you can do to automatically resolve this, but I figured I'd mention the problem and solution.

**Comment by avdgrinten** [comment]
This is not a NetworKit issue but thanks for the suggested workaround.
