### ISSUE TITLE
Core dumped when loading example graph data MIT8.edgelist

### ISSUE THREAD

**Issue by nie93** [kit-parco/networkit#153]
I am trying to import the example graph data from the file `MIT8.edgelist`, but it returns an error message saying `Segmentation fault (core dumped)`, and python stopped eventually.

It also says
```
source "(%rsi)" (0x00000000) not located in a known VMA region (needed readable region)!
```

Can anyone locate the problem? It still works when loading from a smaller size `*.edgelist` file.

**Comment by avdgrinten** [comment]
@kolja-esders Please try to reproduce this issue.

**Comment by avdgrinten** [comment]
We do not have enough info to reproduce this and several new versions have been released in the meantime.
