### ISSUE TITLE
Pip installation failure on MacOS 10.12

### ISSUE THREAD

**Issue by PepSalehi** [kit-parco/networkit#172]
Following the instructions on the [get started page](https://networkit.iti.kit.edu/get_started.html), it seems that networkit was successfully installed. 
<img width="811" alt="screen shot 2018-06-18 at 8 15 34 pm" src="https://user-images.githubusercontent.com/3789755/41568678-05340b42-7335-11e8-951f-137aaee632ef.png">

I have both clang and gcc installed. However, trying to import it in python 3.6 gives the following error:
```
`---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-2-72c757e930cf> in <module>()
----> 1 import networkit

/Users/peyman/anaconda/lib/python3.6/site-packages/networkit/__init__.py in <module>()
     41 # local imports
     42 from . import stopwatch
---> 43 from . import graph
     44 from . import graphio
     45 from . import community

/Users/peyman/anaconda/lib/python3.6/site-packages/networkit/graph.py in <module>()
      1 # extension imports
----> 2 from _NetworKit import Graph, SpanningForest, GraphTools, RandomMaximumSpanningForest, UnionMaximumSpanningForest

ImportError: dlopen(/Users/peyman/anaconda/lib/python3.6/site-packages/_NetworKit.cpython-36m-darwin.so, 2): Symbol not found: __ZTINSt8ios_base7failureB5cxx11E
  Referenced from: /Users/peyman/anaconda/lib/python3.6/site-packages/_NetworKit.cpython-36m-darwin.so
  Expected in: flat namespace
 in /Users/peyman/anaconda/lib/python3.6/site-packages/_NetworKit.cpython-36m-darwin.so`
```

**Comment by PepSalehi** [comment]
The problem was with Anaconda Python, I think. It was fixed after running the conda [installer](https://anaconda.org/vgauthier/networkit):
`conda install -c vgauthier networkit 
`
I suggest this to be added to the get started page. Many people use Anaconda Python and might run into this problem.

**Comment by avdgrinten** [comment]
@kolja-esders can you look into that?
