### ISSUE TITLE
Header files for tests?

### ISSUE THREAD

**Issue by manpen** [kit-parco/networkit#214]
Most of the test cases consist of a header file along the lines of 

```cpp
/*
 * FooBar.h
 *
 *  Created on: look, it's a date
 *      Author: VIP
 */

#ifndef FOOBAR_H_
#define FOOBAR_H_

#include <gtest/gtest.h>
class FooBarGTest: public testing::Test {};

#endif /* FOOBAR_H_ */
```

The only two meaningful lines here are 
```cpp
#include <gtest/gtest.h>
class FooBarGTest: public testing::Test {};
```

I do not see any advantage from having these header files, since the unit tests are meant to be self-contained. On the contrary: they clutter any directory listing, are a nuisance to create, and typically no one reads them.

Am I missing something? Do they have a purpose? Are they required? 
If not, should we get rid of them (or at least do not create them for new code)?

**Comment by avdgrinten** [comment]
I agree. Those headers are useless. We can remove them in the future and they are definitely not needed for new code.

**Comment by avdgrinten** [comment]
This has been resolved.
