### ISSUE TITLE
Curveball Python tests fail

### ISSUE THREAD

**Issue by avdgrinten** [kit-parco/networkit#218]
After merging cmake-pr into Dev, some curveball tests fail. See
https://travis-ci.org/kit-parco/networkit/jobs/414386798
@manpen do you have an idea why that happens? Did we change the signature of `generate()`?

**Comment by manpen** [comment]
I will look at it and issue a PR hopefully today.

**Comment by avdgrinten** [comment]
It is unexpected that this ever worked at all. While it seemed to work in Cython, as far as I'm aware that code would never work in pure Python. Let us just rename the overloaded `generate()` method to `generate_specific()` or remove it entirely.
