### ISSUE TITLE
CentralityGTest GroupDegreeDirected fails randomly

### ISSUE THREAD

**Issue by rbange** [kit-parco/networkit#222]
While rebasing my PR, I recognised that a couple builds fail because of the named test.

I try to reproduce the bug, and it failed in nearly 10% of all cases:

`./networkit_tests --gtest_filter="CentralityGTest.testGroupDegreeDirected"`

I think the problem lays in the combination of a new test case introduced here:
https://github.com/kit-parco/networkit/commit/7fe46a3a3335b700d3ba80f184bddee5fbc9ec94 (the assertion which fails is added here)
and the deletion of a seed in my commit here:
https://github.com/kit-parco/networkit/commit/35a413c8b46b8a281c1f0318e40d0ee1f56af0e7 (seed is removed)

Maybe also the new omp_index might interfere with the this:
https://github.com/kit-parco/networkit/commit/e4c4561c248231445785a3832835400abe02a687

While setting a seed again might be the trivial solution to the problem, is there a way to change the test again so it is independent from a seed again?

Example for failing test in travis:
https://api.travis-ci.org/v3/job/415753016/log.txt

**Comment by avdgrinten** [comment]
@eug93 Please look at this.

**Comment by eug93** [comment]
Hi, I fixed the bugs in the GroupDegree class, it seems to be fine now. However, a [test](https://travis-ci.org/kit-parco/networkit/jobs/417205818) on Travis still fails, but this time the error is not due to the GroupDegree class.

**Comment by eug93** [comment]
Fixed in 29b275044ac3092f56a4b8bbf3d524580da1b92a
