### ISSUE TITLE
pip install fails

### ISSUE THREAD

**Issue by clbarnes** [kit-parco/networkit#282]
Python 3.7, ubuntu 16.04 and kubuntu 18.10, pyenv-virtualenv

`pip install networkit` only works if all of the dependencies, including optional ones, are explicitly installed beforehand. i.e. setuptools is not correctly handling `install_requires` listing. Could this be something to do with importing these requirements from a separate file?

**Comment by avdgrinten** [comment]
This issue has been resolved in the `Dev` branch. With the next release (which is expected next week), this will be fixed for the pip installation, too.
