### ISSUE TITLE
ERROR: NetworKit compilation requires cmake.

### ISSUE THREAD

**Issue by Nikhila123456** [kit-parco/networkit#288]
Hi,
I used python3.7 and installed minGW GCC-8.2.0-3  cmake 3.13.3  ninja 1.8.2,Cython 0.29.3,but pip install networkit gives the error as follows

C:\Users\anjali\AppData\Local\Programs\Python\Python37\Scripts>pip install networkit
Collecting networkit
 Using cached https://files.pythonhosted.org/packages/d4/36/39298b5c1ddccd062505e7e2f9dcb14235ddd158008bda62cdbb907de8e3/networkit-5.0.tar.gz
    Complete output from command python setup.py egg_info:
    ERROR: NetworKit compilation requires cmake.

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\anjali\AppData\Local\Temp\pip-install-c4hcov67\networkit\

Could you provide a solution to fix this

**Comment by avdgrinten** [comment]
A better to solution might be to use WSL - that configuration is supported and works reasonably well.

**Comment by Nikhila123456** [comment]
Thank you for your response.
<http://n.t.s>
Regards,

Nikhila T Suresh
Research Scholar
Dept.of CS & IT
ASAS
Kochi

**Comment by Nikhila123456** [comment]
Thank you for your response.

<http://n.t.s>
Regards,

Nikhila T Suresh
Research Scholar
Dept.of CS & IT
ASAS
Kochi
