### ISSUE TITLE
overview(G) failing for directed graphs

### ISSUE THREAD

**Issue by kolja-esders** [kit-parco/networkit#29]
Produces the following error:

`RuntimeError: Not implemented: Local clustering coefficient is currently not implemted for directed graphs`

We should make sure that `overview` is not failing for directed graphs. I would propose to check whether the graph is directed or not and in case it is directed the clustering coefficient would be omitted. Thoughts?

**Comment by hmeyerhenke** [comment]
Am 04.05.17 um 19:06 schrieb Kolja Esders:
> Produces the following error:
> 
> |RuntimeError: Not implemented: Local clustering coefficient is
> currently not implemted for directed graphs|
> 
> We should make sure that |overview| is not failing for directed graphs.
> I would propose to check whether the graph is directed or not and in
> case it is directed the clustering coefficient would be omitted. Thoughts?

Your suggestion sounds very reasonable.

Thanks,
Henning

**Comment by kolja-esders** [comment]
I also realised that the current clustering coefficient implementation will fail for graphs with self-loops. Will guard against that as well.
