### ISSUE TITLE
Travis setup for Dev branch

### ISSUE THREAD

**Issue by michitux** [kit-parco/networkit#3]
Is there a reason why the travis setup is only present in the master branch? I wanted to suggest a few changes to fix test failures in travis, however according to my understanding the Dev-branch is still the development branch and therefore these changes should go to the Dev-branch. As the Dev-branch contains no travis setup I'm not sure if I should just merge the master branch in the Dev branch for testing my changes or if the master branch is the new development branch (but then the recent changes from the Dev branch should be merged).

[edit] See also [this travis Job](https://travis-ci.org/michitux/networkit/jobs/198810969) which shows that travis doesn't use the configuration from the master branch.

**Comment by kolja-esders** [comment]
Good point. Dev is lacking the travis configuration file. Will merge into Dev.
You're right, Dev is still the development branch.
