### ISSUE TITLE
[Enhancement] Make NKit available in Conda, with regular updates

### ISSUE THREAD

**Issue by lucventurini** [kit-parco/networkit#314]
Dear maintainers, I have started creating a conda recipe for NetworkIt. It will link, for the time being, against the latest version (5.0). 
Once finalised and accepted, it will allow people to directly download networkit within their environment.

However, as I am not directly involved with your (very encomiable!) project, I would prefer not to be the official, or at least not the only official, recipe maintainer.

Is there anyone on your team who could take up the responsibility?
Kind regards

**Comment by avdgrinten** [comment]
Dear Luca,

we would certainly be interested in distributing NetworKit via Conda. The request to support this has been made a few times already. However, we do not have a lot of experience with Conda, especially not with creating packages and publishing them.

However, I am pretty sure that we (@angriman and me) can take the responsibility for maintaining the recipe. I would expect that maintaining it once it works does not require that much effort? (Apart from updates when new versions are published or the build system is modified?)

Best,
Alexander

**Comment by lucventurini** [comment]
Dear @avdgrinten ,
                                 the main difficulty I am having is in creating the recipe itself - unfortunately making sure that the dependencies (ie your `git submodule update --init`) are present where they should, inside the extlibs folder, is proving challenging.

Once that will have been sorted, it should be a matter of updating the version and hash_value variables. Please see the (still not valid) recipe that I have so far.

Kind regards,
Luca
[meta.yaml.txt](https://github.com/kit-parco/networkit/files/3166232/meta.yaml.txt)

**Comment by fabratu** [comment]
Dear @lucventurini,

if the explanation is not to extensive - could you elaborate on the steps necessary in order to create a Conda-package e.g. what to do with the recipe?   

Best,
Fabian

**Comment by avdgrinten** [comment]
@fabratu The recipe has been posted here: https://github.com/conda-forge/staged-recipes/pull/8338

**Comment by fabratu** [comment]
@avdgrinten Thx :)
@lucventurini You can also add me to the maintainer section.

**Comment by lucventurini** [comment]
@fabratu , @avdgrinten 

Thank you for your updates and apologies for the late reply. @fabratu , are you by any chance a Conda forge maintainer? The problem I am having is that the request has been hanging there for a while now without any reviewer. I have contributed different recipes to bioconda, but not to conda-forge, so I am stumped with this last human step.

**Comment by fabratu** [comment]
> @fabratu , are you by any chance a Conda forge maintainer? 

@lucventurini Unfortunately not. After looking at a few merge requests, I would presume the waiting time lately is around 3-5 days after all checks passed. I don't know if pinging other responsible persons would be wise (f.e. chrisburr and xhochy) ...

**Comment by avdgrinten** [comment]
The staged-recipes README has some specific instruction on how to ping the maintainers.

**Comment by lucventurini** [comment]
Hi both, I have added you as maintainers and the checks have been passed.

**Comment by fabratu** [comment]
@lucventurini I updated the meta-file based on the maintainers feedback. Everything is relatively straight forward - except for using tarballs instead of the git-repo. @avdgrinten Question would be whether the package should link to pypi (release-based) or git tarball (e.g. release or dev)?

[meta.yaml.txt](https://github.com/kit-parco/networkit/files/3227789/meta.yaml.txt)

**Comment by avdgrinten** [comment]
How would a tarball from git be produced? I do not think that non-released versions should be installed by default.

Regarding Google Test: Google Test is only required to build the tests (Flag NETWORKIT_BUILD_TESTS for cmake) and should not be required in distribution packages for end-users.

**Comment by fabratu** [comment]
In theory: https://github.com/kit-parco/networkit/tarball/NAME with NAME being a tag or branch without file extension. We could use for example https://github.com/kit-parco/networkit/tarball/master or https://github.com/kit-parco/networkit/tarball/5.0. But based on my limited experience, pypi seems to be the preferred way for conda.

**Comment by fabratu** [comment]
@lucventurini After all your work, it would be nice to finish this package :) Given you have the time - I think it's only a minor step (as posted in the update).

**Comment by lucventurini** [comment]
Hi @fabratu ,
                        many apologies, I have been quite busy in the past weeks! I will try to give it the love it deserves today :-)

**Comment by lucventurini** [comment]
Hi @fabratu , @avdgrinten , the recipe has been updated and seems to compile properly. Waiting for the green light from the Conda forge guys now.

**Comment by lucventurini** [comment]
Hi @fabratu , @avdgrinten , recipe successfully created, approved, and now in Conda Forge :-).
Closing!

**Comment by angriman** [comment]
@lucventurini Great, thank you for your work!

**Comment by avdgrinten** [comment]
Thank you for your work @lucventurini. Regarding the host dependencies: `sphinx`, `ipython` and `jupyter` should not be needed on the build system. If the build currently fails without them, could you open separate issues with the errors encountered?
