### ISSUE TITLE
Provide time for reviews on pull requests

### ISSUE THREAD

**Issue by michitux** [kit-parco/networkit#316]
I would like to suggest to introduce a policy that pull requests must not be merged without first waiting at least some time (like some days or even a week) to allow for feedback (unless it is a trivial change). If we have enough people for giving feedback, this policy could even be extended to disallow merging pull requests without getting at least feedback from one other developer. What do you think about such a policy?

**Comment by angriman** [comment]
Yes I would agree on that, your comments in #315 are right and it would have been beneficial to wait before merging.

**Comment by avdgrinten** [comment]
Sounds reasonable. A week for new features or larger changes seems reasonable to me.

Regarding your comments to #315: This has indeed been merged too quickly. We will revert the commit for now.

**Comment by hmeyerhenke** [comment]
I fully support @michitux here. (i) Allow some time for feedback. (ii) Before starting a new feature, it might even be good to post the plan here for people to comment (unless disclosed for some reason). (iii) Avoid multiple ways of solving the same task (unless there is a very good reason to do so).

**Comment by avdgrinten** [comment]
This has been implemented.
