### ISSUE TITLE
Symlink (still?) needed?

### ISSUE THREAD

**Issue by manpen** [kit-parco/networkit#347]
When building for Windows (which I'm afraid I have to do), I'm always warned about a sym-link which cannot be build. What is this needed for? I could not find a single use case. Can it be removed? 

```CMake
option(NETWORKIT_INCLUDESYMLINK "Create symlink to cpp directory" ON)

#...

if(NETWORKIT_INCLUDESYMLINK)
	if(UNIX)
		add_custom_target(symlink_include ALL
				COMMAND ${CMAKE_COMMAND} -E make_directory "include"
				COMMAND ${CMAKE_COMMAND} -E create_symlink "${PROJECT_SOURCE_DIR}/networkit/cpp" "include/NetworKit")
	else()
		message(WARNING "Cannot create symlink on windows machine")
	endif()
endif()
```

**Comment by avdgrinten** [comment]
IIRC this was a workaround to make NetworKit's headers accessible at a central place before the restructuring the directories. @rbange might remember more. It can be removed now since all headers can be found by passing `-I<source_dir>/include` to the compiler.
