### ISSUE TITLE
Remove website-related files

### ISSUE THREAD

**Issue by kolja-esders** [kit-parco/networkit#38]
The website can now be found under https://github.com/kit-parco/networkit-website.

All related files are thus no longer necessary and should be removed in order to ensure that changes are made to the website repository.

**Comment by avdgrinten** [comment]
What is the progress on that? I guess most of this work is done, although there are a few files in Doc that are linked from the website. Do we want to move/remove them?

**Comment by avdgrinten** [comment]
Commits 108a9e087c67d1aab22c96c997e7f3990bec1d59 2990a31e00bc67470aa724f6bdf35a38c2df9502 5802066fb1128e7107c7e19dd7928a8f9e9f6643 edab0afce5daee070ff6f2176b040ab26b8f5026 clean up the Doc/ directory and remove the website-related files.

**Comment by michitux** [comment]
When trying to access the website repository, I only get a 404 error - I guess this repository is private? Is this intentional? Basically this would mean that there is no more possibility for outsiders to contribute to the DevGuide or the getting started guide once they are really removed from the repository and the only way to access them is through the website.

**Comment by avdgrinten** [comment]
Yes, the current website source (containing `.rst` sources for non-documentation `.html`) is private.

The plan is as follows: The documentation `.rst` files stay in this repository; the output files will of course not be part of any repository. Eventually we will migrate to [readthedocs.io](readthedocs.io), which will automatically build the docs from this repository.

The website will migrate to GitHub pages (in the next few days); this will be a public repository. Eventually, we want to migrate it from `.rst` to markdown and use GitHub's Jekyll to build it. At that point, contributors will be able to easily submit PRs against the website.
