### ISSUE TITLE
Error messages could be made more helpful (or add verbose option?)

### ISSUE THREAD

**Issue by schumannd** [kit-parco/networkit#43]
I had some problems with my c++ headers.

The setup.py simply tries to compile a `sample.cpp` file, but swallows all compilation errors:

Line 135:

```subprocess.call([candidates[v],"-o","test_build","-std={}".format(stdFlags[i]),"-fopenmp","sample.cpp"],stdout=DEVNULL,stderr=DEVNULL)```

I manually removed the `stdout=DEVNULL,stderr=DEVNULL` part and finally got a useful error message other than "ERROR: Test compilation with the following binary names was unsuccessful:..."

There are even some prints (lines 144, 141) in the comments that might be helpful.

I propose the addition of a verbose option, or additional prints of compilation errors to save people some time debugging.

If anyone with a similar problem finds this post, here is the SO article that helped me:
https://stackoverflow.com/questions/19575956/building-c-not-working-in-osx-10-9#19577599

**Comment by kolja-esders** [comment]
Makes sense for sure. We'll resolve that. Thanks!

**Comment by avdgrinten** [comment]
I think this issue has been resolved a long time ago.
