### ISSUE TITLE
Missing function: all simple paths between a source and a target node

### ISSUE THREAD

**Issue by acardona** [kit-parco/networkit#44]
In networkx, we find the function ```all_simple_paths``` which returns a generator of lists, each list specifying a path from a source node to a target node, with a given cutoff length to specify the maximum number of hops. The returned list includes the source (first) and target (last) nodes: https://networkx.github.io/documentation/networkx-1.9/reference/generated/networkx.algorithms.simple_paths.all_simple_paths.html

While in networkit we find related functions such as networkit.distance.APSP (which computes the All-Pairs Shortest-Paths for all nodes in the graph), a function equivalent to ```networkx.all_simple_paths``` is missing.

Given the large performance advantage of networkit over networkx, it would be fantastic to provide a similar function in networkit. We would use it to replace networkx in our application (see: https://github.com/catmaid/CATMAID/issues/1611). Our use case: to discover directed paths of a given length in neuronal circuits (in the jargon: polysynaptic pathways of a given length).

Thanks so much for developing networkit!

**Comment by acardona** [comment]
The function ```networkit.distance.BFS``` might be suitable as a replacement for ```networkx.all_simple_paths```, but it looks like it stops at the first path found and one cannot specify the desired maximum cutoff.

**Comment by hmeyerhenke** [comment]
Dear Albert,

We are considering to offer this feature based on your request, hoping very much that this will make you change to NetworKit!

A student of mine would contact you if you send me your email address. In joint discussions we could find a targeted solution.

Best,
Henning

**Comment by hmeyerhenke** [comment]
BTW, from the zen numbers on their homepage, I would say that NetworKit is faster, probably significantly...

**Comment by acardona** [comment]
Thank you very much, and very exciting to learn about networkit performance. Indeed from what I have read in the documentation, I had every expectation that networkit would outperform other network packages.

I have just joined the mailing list. My academic email is here: https://www.janelia.org/people/albert-cardona Looking forward to communicating with your student.

**Comment by kolja-esders** [comment]
Now available in networkit 4.4.
