### ISSUE TITLE
Adding documentation for top-level python functions

### ISSUE THREAD

**Issue by jstriebel** [kit-parco/networkit#59]
Currently I can not find the top-level python functions in the [Python Documentation](https://networkit.iti.kit.edu/api/modules.html). It would be helpful if they would be added there.

Those functions/objects are currently `getLogLevel, setLogLevel, setPrintLocation, enableNestedParallelism, setNumberOfThreads, getCurrentNumberOfThreads, getMaxNumberOfThreads, none, setSeed`.

**Comment by kolja-esders** [comment]
This should be extended to _all_ methods and classes that are on the top-level. This also includes cases where the method is part of a module but also exposed to the top-level. At the moment, these are: `Graph, Partition, Cover, readGraph, writeGraph, readGraphs, Format`

Especially methods like `readGraph` and `writeGraph` and classes like `Graph` are regularly used in our guides from the top-level. Not having them in the same part in the documentation would probably lead to confusion for users.

**Comment by kolja-esders** [comment]
Will close this issue here since no changes are necessary regarding the core code base. Will be handled on website documentation.

**Comment by jstriebel** [comment]
Perfect, thanks for considering this.
