### ISSUE TITLE
testTopCloseness(Un)directed fails randomly

### ISSUE THREAD

**Issue by michitux** [kit-parco/networkit#6]
The test cases `CentralityGTest.testTopClosenessUndirected` and `CentralityGTest.testTopClosenessDirected` fail randomly and cannot be fixed by providing a random seed at the beginning of the test case. Code for testing:

```
while ./NetworKit-Tests-Opt --gtest_filter=\*testTopClosenessUndirected; do echo ; done
``` 
Probably this is due to the parallel algorithms used. With just one thread I cannot reproduce the problem. Is this an expected behaviour of the used algorithms, i.e. should we expect larger errors in when using multiple threads?

**Comment by ebergamini** [comment]
Fixed bug.
