### ISSUE TITLE
Resolve ApproxBetweeness(2) naming

### ISSUE THREAD

**Issue by kolja-esders** [kit-parco/networkit#8]
Proposed solution:

ApproxBetweeness2 --> EstimateBetweeness
ApproxBetweeness won't change.

TBH I think the new naming is only slightly better. I believe the names are not really clear enough and make it harder for people to decide what to choose.

**Comment by kolja-esders** [comment]
To add to that: Both papers that the algorithms are based on are using "approximation" in their title.

**Comment by kolja-esders** [comment]
Will resolve this issue for now. Feel free to propose a better solution.

**Comment by ebergamini** [comment]
Hi Kolja,

I agree EstimateBetweenness and ApproxBetweenness don’t tell much about how the algorithms work. Nevertheless, I think it’s quite hard to summarize this in one single word. 
A major difference between the two (and the reason why we decided to keep both) is that one has theoretical guarantees on the approximation and the other one is just a heuristic but works better in practice. It is common to use the term “estimation” for heuristics with no guarantees and “approximation” for algorithms with some guarantee on the quality of the approximation (although not everybody follows this convention - as you noticed, both papers use “approximation” in their title).
I think the names are okay, as long as we make clear in the documentation the difference between them and in which cases the user should use one or the other.
Of course, if somebody has suggestions for alternative names, they would be very welcome.
Best,

Elisabetta
