### ISSUE TITLE
Closeness centrality: normalization and maximum misleading / wrong ?!

### ISSUE THREAD

**Issue by hmeyerhenke** [kit-parco/networkit#81]
I recommend that normalization should actually be the default option for closeness centrality as it is in line with most common definitions of closeness.

Also, I believe that the maximum() method is wrong since the maximum value that can be obtained is 1, not 1/(n-1). Or am I missing something?

H.

**Comment by kolja-esders** [comment]
I believe the `maximum` method should adjust the return value based on whether the results were normalized during the `run`. In case of normalization, a maximum value of `1` can be achieved. Otherwise `1 / (N - 1)` should be correct.

**Comment by kolja-esders** [comment]
Using normalization by default seems reasonable to me and would make the implementation a little bit easier to use since you don't have to care about the number of nodes and the `maximum`.

An argument against using normalization by default would be that it is not available for weighted graphs since the distances are weighted. Thoughts?

**Comment by hmeyerhenke** [comment]
Kolja, I think your reasoning is valid. The maximum method needs to check for normalization.

Elisabetta, you are the "closeness expert". What do you think about normalization as the default?

**Comment by ebergamini** [comment]
Yes, I think the normalized definition of closeness (with n-1 in the numerator) is more common and the maximum method should definitely check for normalization.
What is the maximum() method actually supposed to indicate? The node with maximum closeness or the maximum closeness a node could have in a general graph? If the latter is correct, then a maximum() method does not really make sense in case of weighted graphs, right?

**Comment by hmeyerhenke** [comment]
Okay, Kolja, please make the necessary changes regarding normalization and its check in maximum().

I think the maximum() method was introduced by Christian for profiling. I thought you, Elisabetta, would know better than me. Indeed, for weighted graphs it should look different. Thus, a check for weighted/unweighted should be added as well.

Thanks!
