### ISSUE TITLE
Problem installing networkit on Windows 10

### ISSUE THREAD

**Issue by mattpen** [kit-parco/networkit#88]
I was having trouble installing networkit on Windows 10 using WSL as described on your website - https://networkit.iti.kit.edu/get_started.html#id5.  I kept getting this error, even when installing from source:

```
 g++ -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.5m -c networkit/_NetworKit.cpp -o build/temp.linux-x86_64-3.5/networkit/_NetworKit.o -fopenmp -std=c++14 -O3 -DNOGTEST
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    networkit/_NetworKit.cpp:4:20: fatal error: Python.h: No such file or directory
    compilation terminated.
```

Installing the python dev tools fixed the problem and I'm now able to use networkit.  I'm opening this issues to suggest adding `sudo apt-get install python3-dev` to the instructions on your website and possibly to the README here.

**Comment by kolja-esders** [comment]
Hey Matt, thanks for letting us know.

During our testing we didn't encounter this issue, so this is definitely helpful for people with a similar configuration.

Will update the guide accordingly.
